---
- name: Установка и настройка Nginx
  hosts: webservers
  remote_user: user
  become: true
  roles:
    - nginx

  handlers:
    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted